apiVersion: 1.0.0

previews:
  - name: default
    container:
      image: gcr.io/cloudbees-ops-gcr/wombat/sample-app-minimal:${{env.commit.sha}}
      port: 8080
  - name: debug-context
    container:
      image: gcr.io/cloudbees-ops-gcr/wombat/sample-app-minimal:${{env.commit.sha}}
      port: 8080
